version '3.8'


services:
  my-redis-queue:
    image: redis:alpine
    restart: always
    volumes:
      - redis_data:/data
    deploy:
       resources:
          limits:
             memory:200M

  backend_app:
    container_name: backend_app
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - my-redis-queue
    
    env_file:
      - .env
    
    restart: always