name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:


  build_image:
    name: building docker image from build files
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Code Source
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: connect to docker hub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}

      - name: build image and push to docker
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          cache-from: type=registry,ref=blaxinoss/fp_back:latest
          cache-to: type=inline
          platforms: linux/amd64
          build-args: |
            DATABASE_URL=${{ secrets.PRISMA_DATABASE_URL }}
          push: true
          tags: |
            blaxinoss/fp_back:latest
            blaxinoss/fp_back:${{ github.sha }}


  deploy_to_ec2:
      name: Deploy to AWS EC2 via SSH
      needs: build_image
      runs-on: ubuntu-latest
      steps:
        - name: Set up SSH Key
          uses: webfactory/ssh-agent@v0.8.0
          with:
            ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

        - name: Deploy and Restart Docker Compose Service
          uses: appleboy/ssh-action@v1.0.3
          with:
            host: ${{ secrets.EC2_HOST }}
            username: ${{ secrets.EC2_USERNAME }}
            key: ${{ secrets.SSH_PRIVATE_KEY }}
            script: |
              cd ~/comp/
              echo "Pulling latest Docker image..."
              echo "Stopping old service and starting new one..."
              docker compose -f docker-compose.yaml down --remove-orphans
              docker compose -f docker-compose.yaml up -d --force-recreate
              docker ps
              echo "Deployment successful."
      
    
