name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:


  build_image:
    name: building docker image from build files
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Code Source
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: connect to docker hub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}

      - name: build image and push to docker
        uses: docker/build-push-actions@v5
        with:
          context: .
          file: ./Dockerfile
          cache-from: type=registry,ref=blaxinoss/fp_back:latest
          cache-to: type=inline
          platforms: linux/amd64
          push: true
          tags: |
            blaxinoss/fp_back:latest
            blaxinoss/fp_back:${{ github.sha }}
